// Developer Express Code Central Example:
// How to bind the GridColumn Visible property to the dependency property of the ViewModel
// 
// In the v9.3 version, GridColumn properties are not inherited from the
// FrameworkElement class. GridColumn property binding can be done only using the
// BindingOperations.SetBinding method via code. In the v10.1 version, we have
// overcome this issue. You can bind any GridColumn property via xaml.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E2569

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
